### ISSUE TITLE
Dependency 'rtika' is not available for package 'HypothesisReader'

### ISSUE THREAD

**Issue by Awarelessable** [canfielder/CausalityExtraction#1]
I get the following message when trying to install Hypothesis Reader: 

ERROR: dependency 'rtika' is not available for package 'HypothesisReader'. 

Any advice on this?

**Comment by canfielder** [comment]
It appears one of the package dependecies, rtika, is no longer supported on CRAN. Unfortunatley there is nothing you can do right now. I'll have to modify the package dependency structure so rtika, or an alternative, can be sucessfully installed. Thanks for letting me know.

**Comment by canfielder** [comment]
The package has been updated to address this issue. Unfortunately rtika is no longer on CRAN, so cannot be automatically installed as a dependent package when installing HypothesisReader. The rtika package now has to be manually installed along with HypothesisReader. Please see the GitHub repo Readme for specific directions (it's just one additional line of code).
